clean: true
author: Rakuten Group, Inc.
github_url: https://github.com/rakutentech/ios-inappmessaging
module_version: 3.0.0
module: RInAppMessaging
xcodebuild_arguments:
  - -workspace
  - RInAppMessaging.xcworkspace
  - -scheme
  - RInAppMessaging-Example
podspec: RInAppMessaging.podspec
readme: README.md
documentation: "*.md"
hide_documentation_coverage: true
