clean: true
author: Rakuten
github_url: https://github.com/rakutentech/ios-inappmessaging
module_version: 2.1.0
module: RInAppMessaging
xcodebuild_arguments:
  - -workspace
  - RInAppMessaging.xcworkspace.xcworkspace
  - -scheme
  - RInAppMessaging-Example
podspec: RInAppMessaging.podspec
readme: README.md
documentation: "*.md"
hide_documentation_coverage: true
