# Import base_config from git
import_from_git(url: 'https://github.com/rakutentech/ios-buildconfig.git')

platform :ios do
  desc "Build everything"
  lane :ci do |options|
    tests(options)
    coverage
    archive
  end

  desc "Run tests"
  lane :tests do
    cocoapods(repo_update: ENV['REM_FL_CP_REPO_UPDATE'] || false)

    scan(
      clean: true,
      skip_build: true,
      configuration: 'UITests',
      output_directory: './artifacts/ui-tests',
      scheme: ENV['REM_FL_UITESTS_SCHEME'] || 'UITests',
      device: ENV['REM_FL_TESTS_DEVICE'] || 'iPhone 11',
      code_coverage: false,
      slack_only_on_failure: true,
      skip_slack: ENV['PREVIOUS_BUILD_STATUS'] == 'error', # var defined in Bitrise step
      output_types: 'json-compilation-database,html,junit',
      output_files: 'compile_commands.json,report.html,report.junit')

    scan(
      clean: false,
      skip_build: true,
      output_directory: './artifacts/unit-tests',
      scheme: ENV['REM_FL_TESTS_SCHEME'] || 'Tests',
      device: ENV['REM_FL_TESTS_DEVICE'] || 'iPhone 11',
      code_coverage: true,
      slack_only_on_failure: true,
      skip_slack: ENV['PREVIOUS_BUILD_STATUS'] == 'error', # var defined in Bitrise step
      output_types: 'json-compilation-database,html,junit',
      output_files: 'compile_commands.json,report.html,report.junit')

    lint_module
    build_swift_package
  end

  lane :build_swift_package do
    # A fix for incorrect Shock dependencies
    sh 'git config --global url."https://github.com/".insteadOf "git@github.com:"'
    scan(
      clean: true,
      build_for_testing: true,
      scheme: ENV['REM_FL_TESTS_SCHEME'] || 'Tests',
      device: ENV['REM_FL_TESTS_DEVICE'] || 'iPhone 11',
      project: 'SampleSPM/SampleSPM.xcodeproj',
    )
    sh 'git config --global --unset url."https://github.com/".insteadOf'
  end

  lane :coverage do
    slather(
      output_directory: './artifacts/coverage',
      scheme: ENV['REM_FL_TESTS_SCHEME'] || 'Tests',
      sonarqube_xml: true,
      use_bundle_exec: true,
      proj: ENV['REM_FL_TESTS_PROJECT'],
      workspace: ENV['REM_FL_TESTS_WORKSPACE'],
      binary_basename: ENV['REM_FL_TESTS_SLATHER_BASENAME'],
      ignore: '*.{h,m}')
  end

  lane :run_xcov do
    xcov(
      workspace: "RInAppMessaging.xcworkspace",
      scheme: "RInAppMessaging-Example",
      output_directory: "xcov_output",
      include_test_targets: false,
      json_report: true
    )  
  end

  desc "Archive Sample app"
  lane :archive do
    cocoapods(repo_update: ENV['REM_FL_CP_REPO_UPDATE'] || false)

    # Take config URL from env variable or set a dummy one
    config_url = ENV['RIAM_CONFIG_URL'] || 'http://localhost:6789/config'

    xcodebuild(
      archive: true,
      archive_path: "./artifacts/RInAppMessaging.xcarchive",
      scheme: ENV['REM_FL_SAMPLE_SCHEME'],
      workspace: ENV['REM_FL_SAMPLE_WORKSPACE'],
      xcargs: "CODE_SIGN_IDENTITY='' CODE_SIGNING_REQUIRED=NO CODE_SIGNING_ALLOWED=NO ENABLE_BITCODE=NO RIAM_CONFIG_URL=#{config_url}",
    )
  end

  desc "Create and sign ipa from generated xcarchive artifact"
  lane :create_ipa do |options|
    gym(
      skip_build_archive: true,
      export_team_id: options[:export_team_id] || ENV['REM_FL_EXPORT_TEAM_ID'],
      output_directory: "./artifacts",
      include_symbols: true,
      scheme: ENV['REM_FL_SAMPLE_SCHEME'],
      workspace: ENV['REM_FL_SAMPLE_WORKSPACE'],
      output_name: "RInAppMessaging.ipa",
      archive_path: "./artifacts/RInAppMessaging.xcarchive",
      export_options: {
        method: options[:export_method] || "ad-hoc",
        provisioningProfiles: {
          "jp.co.rakuten.inappmessaging.demo" => options[:provisioning_profile]
        }
      },
    )
  end
end
