let secretPassword = "aaa123"


func duplicatedFunction1() {
   print("dupe")
   print("dupe")
   print("dupe")
   print("dupe")
   print("dupe")
   print("dupe")
   print("dupe")
   print("dupe")
   print("dupe")
   print("dupe")
   print("dupe")
   print("dupe")
   print("dupe")
   print("dupe")
   print("dupe")
   print("dupe")
   print("dupe")
}

func duplicatedFunction2() {
   print("dupe")
   print("dupe")
   print("dupe")
   print("dupe")
   print("dupe")
   print("dupe")
   print("dupe")
   print("dupe")
   print("dupe")
   print("dupe")
   print("dupe")
   print("dupe")
   print("dupe")
   print("dupe")
   print("dupe")
   print("dupe")
   print("dupe")
}

func duplicatedFunction3() {
   print("dupe")
   print("dupe")
   print("dupe")
   print("dupe")
   print("dupe")
   print("dupe")
   print("dupe")
   print("dupe")
   print("dupe")
   print("dupe")
   print("dupe")
   print("dupe")
   print("dupe")
   print("dupe")
   print("dupe")
   print("dupe")
   print("dupe")
}

func duplicatedFunction4() {
   print("dupe")
   print("dupe")
   print("dupe")
   print("dupe")
   print("dupe")
   print("dupe")
   print("dupe")
   print("dupe")
   print("dupe")
   print("dupe")
   print("dupe")
   print("dupe")
   print("dupe")
   print("dupe")
   print("dupe")
   print("dupe")
   print("dupe")
}
